"""
Clinical data for DataGenome AI Streamlit prototype.
Converted from src/data.ts (TypeScript) to Python.
"""

CLINICAL_TABLES = [
    {
        "id": "dm",
        "name": "DM",
        "standard": "SDTM",
        "label": "Demographics",
        "rowCount": 250,
        "description": "Contains subject-level characteristics including geographic, administrative, and clinical trial cohort assignments.",
        "columns": [
            {"name": "STUDYID", "type": "VARCHAR(40)", "nullable": False, "isPrimary": True, "isForeign": False,
             "description": "Unique identifier for the clinical trial study.", "cdiscStandard": "SDTM",
             "sampleData": ["STUDY-2026-FIBER", "STUDY-2026-FIBER"]},
            {"name": "USUBJID", "type": "VARCHAR(100)", "nullable": False, "isPrimary": True, "isForeign": False,
             "description": "Unique Subject Identifier spanning all trials and sites.", "cdiscStandard": "SDTM",
             "sampleData": ["01-10023", "01-10024", "02-30045"]},
            {"name": "SUBJID", "type": "VARCHAR(20)", "nullable": False, "isPrimary": False, "isForeign": False,
             "description": "Subject Identifier within a specific study site.", "cdiscStandard": "SDTM",
             "sampleData": ["10023", "10024", "30045"]},
            {"name": "AGE", "type": "INTEGER", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Subject age in years at the time of screening.", "cdiscStandard": "SDTM",
             "sampleData": ["45", "62", "29"]},
            {"name": "SEX", "type": "VARCHAR(2)", "nullable": False, "isPrimary": False, "isForeign": False,
             "description": "Biological sex designation (M = Male, F = Female, U = Unknown).", "cdiscStandard": "SDTM",
             "sampleData": ["M", "F", "F"]},
            {"name": "RACE", "type": "VARCHAR(100)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Self-reported racial classification.", "cdiscStandard": "SDTM",
             "sampleData": ["WHITE", "BLACK OR AFRICAN AMERICAN", "ASIAN"]},
            {"name": "ARMCD", "type": "VARCHAR(20)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Planned Arm Code representing treatment group assignment (e.g., ACT, PLAC, COHORT1).", "cdiscStandard": "SDTM",
             "sampleData": ["ACT", "PLAC", "ACT"]},
            {"name": "ARM", "type": "VARCHAR(100)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Full name of the Planned Arm matching ARMCD.", "cdiscStandard": "SDTM",
             "sampleData": ["Active Treatment Drug X", "Placebo Baseline Control"]},
            {"name": "ACTARMCD", "type": "VARCHAR(20)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Actual Arm Code representing treatment the subject actually received.", "cdiscStandard": "SDTM",
             "sampleData": ["ACT", "PLAC", "ACT"]},
        ]
    },
    {
        "id": "ae",
        "name": "AE",
        "standard": "SDTM",
        "label": "Adverse Events",
        "rowCount": 1140,
        "description": "Records all adverse events experienced by study subjects including severity, seriousness, dates, and MedDRA coding.",
        "columns": [
            {"name": "STUDYID", "type": "VARCHAR(40)", "nullable": False, "isPrimary": True, "isForeign": False,
             "description": "Unique identifier for the clinical trial study.", "cdiscStandard": "SDTM",
             "sampleData": ["STUDY-2026-FIBER"]},
            {"name": "USUBJID", "type": "VARCHAR(100)", "nullable": False, "isPrimary": True, "isForeign": True,
             "foreignTable": "DM", "foreignColumn": "USUBJID",
             "description": "Unique Subject Identifier — FK to DM.USUBJID.", "cdiscStandard": "SDTM",
             "sampleData": ["01-10023", "02-30045"]},
            {"name": "AESEQ", "type": "INTEGER", "nullable": False, "isPrimary": True, "isForeign": False,
             "description": "Sequence number of the adverse event for the subject.", "cdiscStandard": "SDTM",
             "sampleData": ["1", "2", "3"]},
            {"name": "AETERM", "type": "VARCHAR(200)", "nullable": False, "isPrimary": False, "isForeign": False,
             "description": "Verbatim (investigator-reported) adverse event term.", "cdiscStandard": "SDTM",
             "sampleData": ["Headache", "Upper respiratory tract infection"]},
            {"name": "AEDECOD", "type": "VARCHAR(200)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "MedDRA-coded preferred term for the adverse event.", "cdiscStandard": "MedDRA-coded",
             "sampleData": ["Headache", "Upper respiratory tract infection"]},
            {"name": "AEBODSYS", "type": "VARCHAR(200)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "MedDRA System Organ Class (SOC) body system for the event.", "cdiscStandard": "SDTM",
             "sampleData": ["Nervous system disorders", "Infections and infestations"]},
            {"name": "AESEV", "type": "VARCHAR(10)", "nullable": False, "isPrimary": False, "isForeign": False,
             "description": "Severity of the adverse event (MILD, MODERATE, SEVERE).", "cdiscStandard": "SDTM",
             "sampleData": ["MILD", "MODERATE", "SEVERE"]},
            {"name": "AESER", "type": "VARCHAR(1)", "nullable": False, "isPrimary": False, "isForeign": False,
             "description": "Seriousness flag (Y = Serious, N = Not serious).", "cdiscStandard": "SDTM",
             "sampleData": ["N", "Y"]},
            {"name": "AESTDTC", "type": "VARCHAR(10)", "nullable": False, "isPrimary": False, "isForeign": False,
             "description": "Adverse event start date in ISO 8601 format (YYYY-MM-DD).", "cdiscStandard": "SDTM",
             "sampleData": ["2026-01-15", "2026-03-22"]},
            {"name": "AEENDTC", "type": "VARCHAR(10)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Adverse event end/resolution date in ISO 8601 format.", "cdiscStandard": "SDTM",
             "sampleData": ["2026-01-17", "2026-03-25"]},
        ]
    },
    {
        "id": "vs",
        "name": "VS",
        "standard": "SDTM",
        "label": "Vital Signs",
        "rowCount": 3200,
        "description": "Captures all vital sign measurements including blood pressure, heart rate, temperature, and respiratory rate across study visits.",
        "columns": [
            {"name": "STUDYID", "type": "VARCHAR(40)", "nullable": False, "isPrimary": True, "isForeign": False,
             "description": "Unique identifier for the clinical trial study.", "cdiscStandard": "SDTM",
             "sampleData": ["STUDY-2026-FIBER"]},
            {"name": "USUBJID", "type": "VARCHAR(100)", "nullable": False, "isPrimary": True, "isForeign": True,
             "foreignTable": "DM", "foreignColumn": "USUBJID",
             "description": "Unique Subject Identifier — FK to DM.USUBJID.", "cdiscStandard": "SDTM",
             "sampleData": ["01-10023", "02-30045"]},
            {"name": "VSSEQ", "type": "INTEGER", "nullable": False, "isPrimary": True, "isForeign": False,
             "description": "Sequence number of the vital sign observation.", "cdiscStandard": "SDTM",
             "sampleData": ["1", "2", "3"]},
            {"name": "VSTESTCD", "type": "VARCHAR(8)", "nullable": False, "isPrimary": False, "isForeign": False,
             "description": "Short CDISC code for the vital sign test (e.g., SYSBP, DIABP, PULSE).", "cdiscStandard": "SDTM",
             "sampleData": ["SYSBP", "DIABP", "PULSE", "TEMP"]},
            {"name": "VSTEST", "type": "VARCHAR(100)", "nullable": False, "isPrimary": False, "isForeign": False,
             "description": "Full name of the vital sign test.", "cdiscStandard": "SDTM",
             "sampleData": ["Systolic Blood Pressure", "Diastolic Blood Pressure", "Pulse Rate"]},
            {"name": "VSORRES", "type": "VARCHAR(50)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Original result value as reported by the investigator.", "cdiscStandard": "SDTM",
             "sampleData": ["120", "80", "72"]},
            {"name": "VSORRESU", "type": "VARCHAR(20)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Unit of the original result.", "cdiscStandard": "SDTM",
             "sampleData": ["mmHg", "beats/min", "C"]},
            {"name": "VSSTRESC", "type": "VARCHAR(200)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Standardized result in character format for comparison.", "cdiscStandard": "SDTM",
             "sampleData": ["120", "80", "72"]},
            {"name": "VSSTRESN", "type": "FLOAT", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Standardized result in numeric format for analysis.", "cdiscStandard": "SDTM",
             "sampleData": ["120.0", "80.0", "72.0"]},
            {"name": "VSDTC", "type": "VARCHAR(20)", "nullable": False, "isPrimary": False, "isForeign": False,
             "description": "Date/time of the vital sign measurement (ISO 8601).", "cdiscStandard": "SDTM",
             "sampleData": ["2026-02-10T08:15", "2026-02-10T08:20"]},
        ]
    },
    {
        "id": "lb",
        "name": "LB",
        "standard": "SDTM",
        "label": "Laboratory Results",
        "rowCount": 5400,
        "description": "Stores all laboratory test results including hematology, chemistry, urinalysis, and other clinical panels.",
        "columns": [
            {"name": "STUDYID", "type": "VARCHAR(40)", "nullable": False, "isPrimary": True, "isForeign": False,
             "description": "Unique identifier for the clinical trial study.", "cdiscStandard": "SDTM",
             "sampleData": ["STUDY-2026-FIBER"]},
            {"name": "USUBJID", "type": "VARCHAR(100)", "nullable": False, "isPrimary": True, "isForeign": True,
             "foreignTable": "DM", "foreignColumn": "USUBJID",
             "description": "Unique Subject Identifier — FK to DM.USUBJID.", "cdiscStandard": "SDTM",
             "sampleData": ["01-10023", "02-30045"]},
            {"name": "LBSEQ", "type": "INTEGER", "nullable": False, "isPrimary": True, "isForeign": False,
             "description": "Sequence number of the lab result.", "cdiscStandard": "SDTM",
             "sampleData": ["1", "2", "3"]},
            {"name": "LBTESTCD", "type": "VARCHAR(8)", "nullable": False, "isPrimary": False, "isForeign": False,
             "description": "Short CDISC code for lab test (e.g., ALT, AST, WBC, HGB).", "cdiscStandard": "SDTM",
             "sampleData": ["ALT", "AST", "WBC", "HGB", "CREAT"]},
            {"name": "LBTEST", "type": "VARCHAR(100)", "nullable": False, "isPrimary": False, "isForeign": False,
             "description": "Full name of the lab test.", "cdiscStandard": "SDTM",
             "sampleData": ["Alanine Aminotransferase", "Aspartate Aminotransferase", "White Blood Cell Count"]},
            {"name": "LBCAT", "type": "VARCHAR(50)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Category grouping for the lab test panel.", "cdiscStandard": "SDTM",
             "sampleData": ["CHEMISTRY", "HEMATOLOGY", "URINALYSIS"]},
            {"name": "LBSTRESN", "type": "FLOAT", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Numeric standard result for analysis.", "cdiscStandard": "SDTM",
             "sampleData": ["25.4", "30.1", "7.2"]},
            {"name": "LBSTRESU", "type": "VARCHAR(20)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Standard unit of the lab result.", "cdiscStandard": "SDTM",
             "sampleData": ["U/L", "10^9/L", "g/dL"]},
            {"name": "LBNRIND", "type": "VARCHAR(10)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Normal range indicator (LOW, NORMAL, HIGH, CRITICAL).", "cdiscStandard": "SDTM",
             "sampleData": ["NORMAL", "HIGH", "LOW"]},
        ]
    },
    {
        "id": "adsl",
        "name": "ADSL",
        "standard": "ADaM",
        "label": "Subject-Level Analysis Dataset",
        "rowCount": 250,
        "description": "One record per subject containing treatment, safety, and efficacy analysis flags derived from SDTM source data.",
        "columns": [
            {"name": "STUDYID", "type": "VARCHAR(40)", "nullable": False, "isPrimary": True, "isForeign": False,
             "description": "Unique identifier for the clinical trial study.", "cdiscStandard": "ADaM",
             "sampleData": ["STUDY-2026-FIBER"]},
            {"name": "USUBJID", "type": "VARCHAR(100)", "nullable": False, "isPrimary": True, "isForeign": True,
             "foreignTable": "DM", "foreignColumn": "USUBJID",
             "description": "Unique Subject Identifier — FK to DM.USUBJID.", "cdiscStandard": "ADaM",
             "sampleData": ["01-10023", "02-30045"]},
            {"name": "TRT01P", "type": "VARCHAR(100)", "nullable": False, "isPrimary": False, "isForeign": False,
             "description": "Planned Treatment for Period 1 (full label).", "cdiscStandard": "ADaM",
             "sampleData": ["Active Treatment Drug X", "Placebo Baseline Control"]},
            {"name": "TRT01A", "type": "VARCHAR(100)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Actual Treatment for Period 1 (may differ from planned).", "cdiscStandard": "ADaM",
             "sampleData": ["Active Treatment Drug X", "Placebo Baseline Control"]},
            {"name": "SAFFL", "type": "VARCHAR(1)", "nullable": False, "isPrimary": False, "isForeign": False,
             "description": "Safety Population Flag (Y = included in safety analysis).", "cdiscStandard": "ADaM",
             "sampleData": ["Y", "N"]},
            {"name": "ITTFL", "type": "VARCHAR(1)", "nullable": False, "isPrimary": False, "isForeign": False,
             "description": "Intent-to-Treat Population Flag (Y = included in ITT analysis).", "cdiscStandard": "ADaM",
             "sampleData": ["Y", "N"]},
            {"name": "AGEGR1", "type": "VARCHAR(20)", "nullable": True, "isPrimary": False, "isForeign": False,
             "description": "Age group classification (e.g., <65, >=65) for stratified analysis.", "cdiscStandard": "ADaM",
             "sampleData": ["<65", ">=65"]},
        ]
    }
]


GLOSSARY = [
    {
        "term": "MedDRA",
        "standard": "MedDRA",
        "category": "Terminology Standards",
        "definition": "Medical Dictionary for Regulatory Activities. A rich standardized hierarchical terminology of clinical entries representing diagnoses, medical histories, indications, and reactions.",
        "example": "Provides a five-level structure: SOC (System Organ Class) → HLGT → HLT → PT (Preferred Term) → LLT (Lowest Level Term).",
        "code": "ICH-MedDRA-29.0"
    },
    {
        "term": "SDTM",
        "standard": "SDTM",
        "category": "Data Standards",
        "definition": "Study Data Tabulation Model. The foundational clinical schema specification mandated by the FDA and PMDA for tabular clinical trial data submissions.",
        "example": "Consists of specific domains representing clinical actions: DM (Demographics), AE (Adverse Events), LB (Lab Tests).",
        "code": "CDISC-SDTM-v2.0"
    },
    {
        "term": "ADaM",
        "standard": "ADaM",
        "category": "Analysis Standards",
        "definition": "Analysis Data Model. A dataset model structure standardizing content structures designed explicitly for statistical analysis trials, SAS exports, and CDISC compliance.",
        "example": "Ensures predictability by enforcing subject-level analysis (ADSL) file foundations.",
        "code": "CDISC-ADaM-v2.1"
    },
    {
        "term": "USUBJID",
        "standard": "SDTM",
        "category": "Domain Identifiers",
        "definition": "Unique Subject Identifier. A standard variable that uniquely identifies a research participant across the entire clinical studies submission.",
        "example": "A concatenation of Study, Site, and Subject ID (e.g., STUDY-201-SITE12-SUBJ034).",
        "code": None
    },
    {
        "term": "AESEV",
        "standard": "SDTM",
        "category": "Adverse Event Variables",
        "definition": "Adverse Event Severity. Demarcates the degree of discomfort or disruption of function associated with an AE (MILD, MODERATE, SEVERE).",
        "example": "Subject experienced severe headache resulting in missed dosing, coded AESEV = SEVERE.",
        "code": None
    },
    {
        "term": "GCP",
        "standard": "GCP",
        "category": "Regulatory Compliance",
        "definition": "Good Clinical Practice. An international ethical and scientific quality standard for designing, conducting, recording, and reporting trials that involve human subjects.",
        "example": "ICH E6(R2) GCP guidance mandates written informed consent before any study-related activities.",
        "code": "ICH-E6-R2"
    },
    {
        "term": "ALCOA+",
        "standard": "GCP",
        "category": "Data Integrity",
        "definition": "Attributable, Legible, Contemporaneous, Original, Accurate — plus Complete, Consistent, Enduring, Available. Core data integrity principles for clinical records.",
        "example": "An eCRF entry should be timestamped at the time of collection (Contemporaneous) and never altered without audit trail (Original).",
        "code": None
    },
    {
        "term": "ITT",
        "standard": "ADaM",
        "category": "Analysis Populations",
        "definition": "Intent-to-Treat. An analysis strategy where all randomized subjects are included in the analysis as randomized, regardless of protocol deviations.",
        "example": "ITTFL = 'Y' in ADSL identifies subjects included in the ITT population for primary efficacy analysis.",
        "code": None
    },
    {
        "term": "SAF",
        "standard": "ADaM",
        "category": "Analysis Populations",
        "definition": "Safety Population. Typically includes all subjects who received at least one dose of study treatment, used for adverse event analysis.",
        "example": "SAFFL = 'Y' in ADSL marks subjects eligible for safety analyses including AE incidence tables.",
        "code": None
    },
    {
        "term": "CDISC",
        "standard": "SDTM",
        "category": "Data Standards",
        "definition": "Clinical Data Interchange Standards Consortium. A non-profit standards organization developing data standards for clinical research.",
        "example": "CDISC standards include SDTM, ADaM, CDASH, and SEND used globally for FDA and PMDA submissions.",
        "code": None
    },
    {
        "term": "RWE",
        "standard": "RWE",
        "category": "Evidence Generation",
        "definition": "Real-World Evidence. Clinical evidence about the usage and potential benefits or risks of a medical product derived from analysis of real-world data (RWD) outside clinical trials.",
        "example": "EHR data from hospital networks analyzed post-approval to monitor long-term drug safety signals.",
        "code": None
    },
    {
        "term": "PARAMCD",
        "standard": "ADaM",
        "category": "Analysis Variables",
        "definition": "Parameter Code. A short code variable in ADaM datasets identifying the analysis parameter (e.g., SYSBP for Systolic Blood Pressure).",
        "example": "In ADLB, PARAMCD = 'ALT' and PARAM = 'Alanine Aminotransferase (U/L)'.",
        "code": None
    },
    {
        "term": "SAE",
        "standard": "MedDRA",
        "category": "Safety Reporting",
        "definition": "Serious Adverse Event. Any adverse event that results in death, is life-threatening, requires hospitalization, or causes significant disability.",
        "example": "AE records with AESER = 'Y' must be expedited to the Sponsor within 24 hours of site awareness.",
        "code": None
    },
]


MOCK_DQ_ISSUES = [
    {
        "id": "dq-1",
        "tableId": "dm",
        "columnName": "ARMCD",
        "issueType": "Missing/Null",
        "count": 12,
        "percentage": 4.8,
        "severity": "Critical",
        "description": "Found 12 subjects that completed screening but have blank treatment arm codes (ARMCD) with actual active trial participation.",
        "remediation": "Cross-reference active dispensing logs from Interactive Response Technology (IRT) system to populate missing cohort parameters."
    },
    {
        "id": "dq-2",
        "tableId": "vs",
        "columnName": "VSSTRESN",
        "issueType": "Negative Value",
        "count": 3,
        "percentage": 0.09,
        "severity": "Critical",
        "description": "Vital Signs standard results (VSSTRESN) contain negative numbers for Diastolic Blood Pressure (e.g., -12 mmHg, -5 mmHg) which are physiologically impossible.",
        "remediation": "Flag records with the site coordinator for immediate source data verification (SDV) and eCRF corrective editing."
    },
    {
        "id": "dq-3",
        "tableId": "ae",
        "columnName": "AESTDTC",
        "issueType": "Future Date",
        "count": 2,
        "percentage": 0.17,
        "severity": "Warning",
        "description": "Adverse Event start date (AESTDTC) contains dates in the future (e.g., 2027-10-12 and 2028-01-05), exceeding screening database lock targets.",
        "remediation": "Review investigator diary inputs to resolve transcription year-typos during medical history updates."
    },
    {
        "id": "dq-4",
        "tableId": "dm",
        "columnName": "USUBJID",
        "issueType": "Duplicate PK",
        "count": 4,
        "percentage": 1.6,
        "severity": "Critical",
        "description": "Demographics table contains non-unique PK rows for USUBJID (e.g. 01-10023 present twice with conflicting geographic identifiers).",
        "remediation": "Consolidate multiple registry cards into single distinct subject records. Retract duplicate eCRFs at site levels."
    },
    {
        "id": "dq-5",
        "tableId": "lb",
        "columnName": "LBSTRESN",
        "issueType": "Missing/Null",
        "count": 145,
        "percentage": 2.68,
        "severity": "Warning",
        "description": "Laboratory results column is missing numeric outputs for ALT and AST tests despite LBCAT chemistry classifications showing test completions.",
        "remediation": "Verify whether physical samples experienced hemolysis or lab interface transmissions failed, then re-import local values."
    },
    {
        "id": "dq-6",
        "tableId": "ae",
        "columnName": "AEENDTC",
        "issueType": "Constraint Violation",
        "count": 5,
        "percentage": 0.43,
        "severity": "Warning",
        "description": "Adverse Event resolution end date (AEENDTC) precedes active start dates (AESTDTC). Logical constraint contradiction.",
        "remediation": "Audit date timestamps on associated Case Report Forms. Adjust standard chronologies to align recovery logs properly."
    },
]
